### ISSUE TITLE
Filter incoming logs using grep

### ISSUE THREAD

**Issue by markandrewkato** [theproductiveprogrammer/pino-mysql#1]
Hi! Is it possible to filter incoming logs using grep? I've tried this but it doesn't work for me

`node build/server.js | grep -v "started server" | ./node_modules/.bin/pino-mysql -c pino-db-config.json`

This doesn't log to the database.

**Comment by theproductiveprogrammer** [comment]
Hi @markandrewkato 

This is not a problem with `pino-mysql` but is because `grep` is buffering your input stream.

```
node build/server.js | grep -v "started server" | ./node_modules/.bin/pino-mysql -c pino-db-config.json
                        == BUFFERED HERE ==
```

Most `grep` implementations have a way to turn this off. The option `--line-buffered` works for mine:

```
node build/server.js | grep -v "started server" --line-buffered | ./node_modules/.bin/pino-mysql -c pino-db-config.json
```

**Comment by markandrewkato** [comment]
@theproductiveprogrammer Thank you very much for the help! Will check.
